//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phu_NET.Chuong6.Ex3
{


    public partial class Ex3_ThietLapNhanVien
    {
    }
}
